// Sanastot. Lisää uusia settejä alla olevaan listaan.
// Muoto: { fi: "suomi", en: "english" }
// Voit lisätä myös vihjeen: { fi: "...", en: "...", hint: "vihje" }

window.VOCAB = {
  sets: [
    {
      id: "education",
      name: "Theme vocabulary 1: Education",
      description: "ENA6.7 Spring26 — Theme 1: Learning curves.",
      cards: [
        // SCHOOLS & INSTITUTIONS
        { fi: "kansalaisopisto", en: "adult education centre" },
        { fi: "oppisopimuskoulutus", en: "apprenticeship training" },
        { fi: "perusopetus", en: "basic education" },
        { fi: "sisäoppilaitos", en: "boarding school" },
        { fi: "peruskoulu", en: "comprehensive school" },
        { fi: "alakoulu", en: "elementary school" },
        { fi: "kansanopisto", en: "folk high school" },
        { fi: "lukio", en: "general upper secondary school" },
        { fi: "avoin yliopisto", en: "open university" },
        { fi: "esikoulu", en: "preschool" },
        { fi: "yksityiskoulu", en: "public school" },
        { fi: "yläkoulu", en: "secondary school" },
        { fi: "yliopisto", en: "university" },
        { fi: "ammattikorkeakoulu", en: "university of applied sciences" },
        { fi: "ammattiopisto", en: "vocational college" },

        // SCHOOL LIFE
        { fi: "poissaolo", en: "absence" },
        { fi: "syventävät opinnot", en: "advanced studies" },
        { fi: "sisäänpääsy", en: "admission" },
        { fi: "ylioppilastutkinto Britanniassa", en: "A-levels" },
        { fi: "käydä oppitunneilla", en: "attend lessons" },
        { fi: "arviointi", en: "assessment" },
        { fi: "tehtävä", en: "assignment" },
        { fi: "tauko", en: "break" },
        { fi: "luntata", en: "cheat" },
        { fi: "pakollinen", en: "compulsory" },
        { fi: "valmennuskurssi", en: "cram course" },
        { fi: "opintopiste", en: "credit / study credit" },
        { fi: "opetussuunnitelma", en: "curriculum" },
        { fi: "jälki-istunto", en: "detention" },
        { fi: "kuri", en: "discipline" },
        { fi: "etäopiskelu", en: "distance learning" },
        { fi: "jättää koulu kesken", en: "drop out" },
        { fi: "e-oppiminen", en: "e-learning" },
        { fi: "erottaa koulusta", en: "expel" },
        { fi: "koulutuntien ulkopuolinen toiminta", en: "extracurricular activities" },
        { fi: "reputtaa", en: "fail" },
        { fi: "koululuokka", en: "form" },
        { fi: "hyppytunti", en: "free period" },
        { fi: "valmistua", en: "graduate from" },
        { fi: "oppitunti", en: "lesson" },
        { fi: "arvosana", en: "mark" },
        { fi: "ylioppilastutkinto Suomessa", en: "matriculation examination" },
        { fi: "valinnainen", en: "optional" },
        { fi: "läpäistä koe", en: "pass" },
        { fi: "pinnata", en: "skip a lesson" },
        { fi: "opintojakso", en: "study unit" },
        { fi: "erottaa määräajaksi", en: "suspend" },
        { fi: "opinto-ohjelma", en: "syllabus" },
        { fi: "lukukausi", en: "term" },
        { fi: "lukujärjestys", en: "timetable" },

        // STAFF
        { fi: "luokanopettaja", en: "class teacher" },
        { fi: "luokanvalvoja", en: "form teacher" },
        { fi: "opinto-ohjaaja", en: "guidance counsellor" },
        { fi: "rehtori", en: "head teacher" },
        { fi: "kuraattori", en: "school social worker" },
        { fi: "erityisopettaja", en: "special education teacher" },
        { fi: "aineenopettaja", en: "subject teacher" },

        // HIGHER EDUCATION
        { fi: "oppilaitoksesta valmistuneet opiskelijat", en: "alumni" },
        { fi: "hakemus oppilaitokseen", en: "application for admission" },
        { fi: "väitöskirja", en: "dissertation" },
        { fi: "opiskelija-asuntola", en: "hall of residence" },
        { fi: "kirjoittautua sisään", en: "enrol on" },
        { fi: "tiedekunta", en: "faculty" },
        { fi: "saada loppututkinto", en: "get a degree" },
        { fi: "päästä yliopistoon", en: "get into university" },
        { fi: "luento", en: "lecture" },
        { fi: "pääaine", en: "major" },
        { fi: "sivuaine", en: "minor" },
        { fi: "motivaatiokirje", en: "personal statement" },
        { fi: "stipendi", en: "scholarship" },
        { fi: "opintolaina", en: "student loan" },
        { fi: "apuraha", en: "study grant" },
        { fi: "osallistua pääsykokeeseen", en: "take an entrance exam" },
        { fi: "tutkielma", en: "thesis" },
        { fi: "lukukausimaksu", en: "tuition fee" }
      ]
    },
    {
      id: "working-life",
      name: "Theme vocabulary 2: Working life",
      description: "ENA6.7 Spring26 — Theme 2: Work in progress.",
      cards: [
        // PEOPLE
        { fi: "hakija", en: "applicant" },
        { fi: "toimitusjohtaja", en: "CEO, chief executive officer" },
        { fi: "työkaveri", en: "colleague, co-worker" },
        { fi: "työntekijä", en: "employee" },
        { fi: "työnantaja", en: "employer" },
        { fi: "yrittäjä", en: "entrepreneur, self-employed" },
        { fi: "esihenkilö", en: "foreman, superior" },
        { fi: "johto", en: "management" },
        { fi: "johtaja, pomo", en: "manager, director" },
        { fi: "toimistotyöntekijä", en: "office worker" },
        { fi: "henkilökunta", en: "personnel, staff" },
        { fi: "alainen", en: "subordinate" },
        { fi: "työnjohtaja, tarkastaja, esihenkilö", en: "supervisor" },
        { fi: "tilapäistyöntekijä", en: "temporary worker, temp" },
        { fi: "harjoittelija", en: "trainee, apprentice, intern" },
        { fi: "työtön", en: "unemployed, jobless" },
        { fi: "työvoima, henkilöstö", en: "workforce, labour force" },

        // GETTING A JOB
        { fi: "hakemus", en: "application" },
        { fi: "hakea työpaikkaa", en: "apply for a job" },
        { fi: "ansioluettelo", en: "curriculum vitae / CV / résumé" },
        { fi: "työpaikkahaastattelu", en: "job interview" },
        { fi: "työtarjous", en: "job offer" },
        { fi: "suositus", en: "reference" },
        { fi: "avoin työpaikka", en: "vacancy / vacant position" },

        // GENERAL
        { fi: "oppisopimus", en: "apprenticeship" },
        { fi: "ura", en: "career" },
        { fi: "työtodistus", en: "certificate of employment" },
        { fi: "työehtosopimus", en: "collective bargaining agreement" },
        { fi: "provisiopalkka", en: "commission" },
        { fi: "yhtiö, yritys", en: "company / business / enterprise" },
        { fi: "irtisanoa", en: "dismiss / give notice / make redundant" },
        { fi: "ansaita", en: "earn" },
        { fi: "antaa potkut", en: "fire someone" },
        { fi: "liukuva työaika", en: "flexitime / flexible hours" },
        { fi: "luontoisedut", en: "fringe benefits / perks" },
        { fi: "kokopäivätyö", en: "full-time job" },
        { fi: "keikkatalous", en: "gig economy" },
        { fi: "mennä lakkoon", en: "go on strike" },
        { fi: "palkata", en: "hire / employ / recruit" },
        { fi: "työpisteiden jakaminen", en: "hybrid work" },
        { fi: "tulot, ansio", en: "income" },
        { fi: "lähikokous", en: "in-person meeting" },
        { fi: "ammatti", en: "job, occupation" },
        { fi: "TE-toimisto", en: "job centre / employment agency", hint: "työ- ja elinkeinotoimisto" },
        { fi: "lomauttaa", en: "lay off", hint: "temporarily" },
        { fi: "virkavapaa", en: "leave of absence" },
        { fi: "ansaita elantonsa", en: "make a living / earn a living" },
        { fi: "ruumiillinen, käsin tehty työ", en: "manual work" },
        { fi: "pimeä työ", en: "moonlighting" },
        { fi: "lähityö", en: "on-site work" },
        { fi: "avokonttori", en: "open-plan office" },
        { fi: "perehdyttäminen", en: "orientation" },
        { fi: "osa-aikatyö", en: "part-time work" },
        { fi: "palkka", en: "pay / salary / wages" },
        { fi: "palkankorotus", en: "pay rise" },
        { fi: "eläke", en: "pension" },
        { fi: "vakituinen työpaikka", en: "permanent job" },
        { fi: "urakkatyö", en: "piecework" },
        { fi: "virka", en: "post" },
        { fi: "toimitilat", en: "premises" },
        { fi: "akateeminen ammatti", en: "profession" },
        { fi: "ylennys", en: "promotion" },
        { fi: "pätevöityä", en: "qualify" },
        { fi: "etäkokous", en: "remote meeting" },
        { fi: "etätyö", en: "remote work" },
        { fi: "irtisanoutua, erota", en: "resign / quit" },
        { fi: "jäädä eläkkeelle", en: "retire" },
        { fi: "eläköityminen", en: "retirement" },
        { fi: "työvuorolista", en: "rota" },
        { fi: "vuorotyö", en: "shift work" },
        { fi: "pätkätyö, väliaikainen työ, keikkatyö", en: "short-term contract / temporary job" },
        { fi: "sairausloma", en: "sick leave" },
        { fi: "lakko", en: "strike" },
        { fi: "valvoa, ohjata, johtaa", en: "supervise" },
        { fi: "ammattiyhdistys, palkansaajajärjestö", en: "trade union" },
        { fi: "työttömyys", en: "unemployment" },
        { fi: "työttömyyskorvaus", en: "unemployment benefit / dole", hint: "BrE" },
        { fi: "vapaaehtoistyö", en: "volunteering / volunteer work" },
        { fi: "työolosuhteet", en: "work conditions" },
        { fi: "työsopimus", en: "work contract" },
        { fi: "työaika", en: "working hours" },
        { fi: "työharjoittelu", en: "work practice / internship" },
        { fi: "tehdä ylitöitä", en: "work overtime" },
        { fi: "tehdä vuorotyötä", en: "work shifts" },
        { fi: "nollatuntisopimus", en: "zero-hour contract" }
      ]
    },
    {
      id: "economy",
      name: "Theme vocabulary 3: Economy",
      description: "ENA6.7 — Theme 3: Hand of the market. Personal finances, investing, general economy & word pairs.",
      cards: [
        // PERSONAL FINANCES
        { fi: "tili", en: "account", hint: "personal finances" },
        { fi: "pankkiautomaatti", en: "ATM", hint: "automated teller machine" },
        { fi: "saldo", en: "balance" },
        { fi: "budjetti, tulo- ja menoarvio", en: "budget" },
        { fi: "käteinen", en: "cash" },
        { fi: "velka", en: "debt" },
        { fi: "tallettaa", en: "deposit", hint: "verbi: laittaa rahaa tilille" },
        { fi: "käsiraha, vakuus", en: "down payment" },
        { fi: "kulu, meno", en: "expense" },
        { fi: "rahoittaa, rahoitus", en: "finance" },
        { fi: "tulovero", en: "income tax" },
        { fi: "osamaksu", en: "instalment payment" },
        { fi: "korko", en: "interest", hint: "pankkitermi" },
        { fi: "asuntolaina", en: "mortgage" },
        { fi: "ylittää tili", en: "overdraw" },
        { fi: "pikavippi", en: "payday loan" },
        { fi: "kuitti", en: "receipt" },
        { fi: "tilitapahtuma", en: "transaction" },
        { fi: "varallisuus", en: "wealth" },
        { fi: "nosto", en: "withdrawal" },

        // INVESTING
        { fi: "omaisuus, varat", en: "assets" },
        { fi: "joukkovelkakirja", en: "bond" },
        { fi: "romahdus", en: "crash" },
        { fi: "osinko", en: "dividend" },
        { fi: "sijoittaa", en: "invest" },
        { fi: "sijoitus", en: "investment" },
        { fi: "sijoitusrahasto", en: "investment fund" },
        { fi: "kiinteistö, omaisuus", en: "property" },
        { fi: "osake", en: "share" },
        { fi: "osakas, osakkeenomistaja", en: "shareholder" },
        { fi: "pörssi", en: "stock market" },
        { fi: "osakekanta, arvopaperit", en: "stocks" },
        { fi: "käydä kauppaa, kaupankäynti", en: "trade" },

        // GENERAL ECONOMY
        { fi: "maksukyvytön, vararikossa", en: "bankrupt" },
        { fi: "konkurssi", en: "bankruptcy" },
        { fi: "pääoma", en: "capital" },
        { fi: "veloittaa, veloitus", en: "charge" },
        { fi: "kuluttaja", en: "consumer" },
        { fi: "kulutus", en: "consumption" },
        { fi: "rahayksikkö, valuutta", en: "currency" },
        { fi: "lama", en: "depression" },
        { fi: "taloustiede", en: "economics" },
        { fi: "talous", en: "economy" },
        { fi: "kauppasaarto", en: "embargo" },
        { fi: "kauppatavara", en: "goods" },
        { fi: "inflaatio", en: "inflation" },
        { fi: "lasku, laskuttaa", en: "invoice" },
        { fi: "markkinoida, markkina(t)", en: "market" },
        { fi: "taantuma", en: "recession" },
        { fi: "palauttaa, takaisinmaksu", en: "refund" },
        { fi: "liikevaihto", en: "revenue" },
        { fi: "arvonlisävero", en: "value added tax", hint: "VAT" },

        // WORD PAIRS
        { fi: "(nopea) nousukausi", en: "boom" },
        { fi: "(nopea) laskukausi", en: "slump" },
        { fi: "härkämarkkina, pitkä nousukausi", en: "bull market" },
        { fi: "karhumarkkina, pitkä laskukausi", en: "bear market" },
        { fi: "pankkikortti", en: "debit card" },
        { fi: "luottokortti", en: "credit card" },
        { fi: "alijäämä", en: "deficit" },
        { fi: "ylijäämä", en: "surplus" },
        { fi: "laskusuhdanne", en: "downturn" },
        { fi: "noususuhdanne", en: "upturn" },
        { fi: "viedä maasta, vienti", en: "export" },
        { fi: "tuoda maahan, maahantuonti", en: "import" },
        { fi: "tappiolla", en: "in the red" },
        { fi: "voitolla", en: "in the black" },
        { fi: "tappio", en: "loss" },
        { fi: "tuotto, voitto", en: "profit" },
        { fi: "netto", en: "net" },
        { fi: "brutto", en: "gross" },
        { fi: "tarjonta", en: "supply" },
        { fi: "kysyntä", en: "demand" }
      ]
    }
  ]
};
